### ISSUE TITLE
Warnings%Error

### ISSUE THREAD

**Issue by Whynot295** [caomuqing/neptune#1]
After downloaded the package from this website and set up according to the process as well as installed gurobi and add it to the path as needed, there are some warnings while catkin build:
1. catkin_package() depends on 'decomp_util_LIBRARIES' is defined.
2. In file included fromfrom /home/carycui/catkin ws_neptune/build/separator/glpkdownload/src/src/env/stdc.h:37，from /home/carycui/catkin ws_neptune/build/separator/glpkdownload/src/src/env/env.h:27，from /home/carycui/catkin ws neptune /build/separator/glpkdownload/src/src/misc/wclique1.c:24:In function 'memset
inlined from 'glp_wclique1’at /home/carycui/catkin ws_neptune/build/separator/glpk-download/src/src/misc/wclique1.c:113:7:
3. catkin package() include dir'/home/carycui/catkin_ws_neptune_v11/build/separator/glpk-download/install/inlude!
should be placed in the devel space instead of the build space
4. WARNING: Target "neptune test node" requests linking to directory "/home/carycuilopt/gurobi912/linux64/lib/". Targets may link only to libraries.CMake is dropping theitem.
5. ERROR: cannot launch node of type [neptune/heptune_test_node]: Cannot locate node of type [neptune test hode] in package neptune], Make sure file exists in package path and permission is set to executable (chmod +x)
Specificly, it seems that I can't start the launch node and the libraries are missing even after I downloaded them.The pictures are as follows:

![1-5](https://github.com/caomuqing/neptune/assets/128035413/774eb5ae-4c30-42ec-9d7e-c0e97ca03ac3)

![1-1](https://github.com/caomuqing/neptune/assets/128035413/b3862f90-49b2-4bcb-b8a6-68d4fe1cf4fd)

![1-2](https://github.com/caomuqing/neptune/assets/128035413/9b68ab65-eefd-4a30-8734-2dc4f9905f3a)

![1-3](https://github.com/caomuqing/neptune/assets/128035413/b0704dce-1a97-42da-af1e-acbe576ae5ad)

![1-4](https://github.com/caomuqing/neptune/assets/128035413/76d58d99-bc18-40d3-a7b8-2dd702c6c523)

![1-5](https://github.com/caomuqing/neptune/assets/128035413/f054f784-0c3a-4ca5-9885-c8b490c89994)

![2-1](https://github.com/caomuqing/neptune/assets/128035413/88e14cd5-dba8-4c23-8167-c4453be49da3)

**Comment by caomuqing** [comment]
Hi Cary,

thanks for using this package. It looks like the screenshots show only warnings that do not affect building the package. There should be another error (indicated by error or ERROR) when you are trying to build. Can you scroll up the terminal and try to find the exact error message that causes building failure?

mq

**Comment by Whynot295** [comment]
Sure.
I will try again this afternoon and find the exact Error. Thanks a lot!
Cary




---- Replied Message ----
| From | Cao ***@***.***> |
| Date | 07/18/2023 12:31 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [caomuqing/neptune] Warnings%Error (Issue #1) |

Hi Cary,

thanks for using this package. It looks like the screenshots show only warnings that do not affect building the package. There should be another error (indicated by error or ERROR) when you are trying to build. Can you scroll up the terminal and try to find the exact error message that causes building failure?

mq

**Comment by Whynot295** [comment]
Here's the error while catkin build:
![error](https://github.com/caomuqing/neptune/assets/128035413/03a173eb-6fb3-4f8b-aecd-faac964cf616)
![error2](https://github.com/caomuqing/neptune/assets/128035413/35be3b33-4f92-4485-b31f-5715518d5aa8)
And this is the error while launching the neptune_single_benchmark.sh, the Rviz can be opened but there's nothing showing up on the background.
![error3](https://github.com/caomuqing/neptune/assets/128035413/2424c6bb-95d5-4e8f-b344-448746b633b5)

**Comment by caomuqing** [comment]
I have made some edits, please pull the latest commit and see if it builds successfully.

**Comment by Whynot295** [comment]
Awesome! Catkin build is now successful with no errors but only a few warnings. Do I need to heed these warnings and do some workaround? 
I noticed that part of the code has been commented out. Now the base points can appear when opening rviz, but the problem of not finding nodes after opening still exists, and the process of object searching and finding paths cannot appear. What is the reason for this?
Should I add something or should I check some options to show the path?
I really appreciate your help!

![succsee](https://github.com/caomuqing/neptune/assets/128035413/d7711f27-aaff-4403-bfeb-feae8490509d)
![error3](https://github.com/caomuqing/neptune/assets/128035413/6d9e65a1-812f-4f8d-a0ff-2293ba6c0803)
![rviz](https://github.com/caomuqing/neptune/assets/128035413/10e180b8-92ef-446d-b08e-8d4cb785b075)
![add](https://github.com/caomuqing/neptune/assets/128035413/e156f5d0-0750-43a0-ad42-ccf4a0b59844)

**Comment by caomuqing** [comment]
The warnings are ok, they usually do not affect running.
It looks like the setup.bash wasn't sourced correctly.  You may try `source devel/setup.bash` in a new terminal in folder catkin_ws_neptune and then `roslaunch neptune neptune_single_benchmark.launch quad:=firefly1`. See if it works.

**Comment by Whynot295** [comment]
So sorry that I wasn't able to operate for the last few days. After I tried the source file and the launch file as you told me, the two commands now work well, but the image is still the same as before, as shown in the picture, it shows the target's position and obstacles, the process of trajectory-searching and the actual route are missing. I don't think it's a source problem because I still can't generate a route after executing the instructions in the launch file one by one. I checked the display settings and most of them are good. It seems there's TF data missing , could that be the problem? 
As your article shows, the route consists of three lines of different colors, including the path generated by Kim's method, the trajectory generated by the front-end trajectory finder, and the actual trajectory after optimization. I want to figure out how the programming works and show the process in image so that I can see the effect more intuitively. If possible, I hope I can use different vichels to achieve some functions, which will be very helpful for my research content. Thanks a lot for your help!
![goal_image](https://github.com/caomuqing/neptune/assets/128035413/07c13370-96a4-4de5-ac6d-e883f94e9d61)
![displays](https://github.com/caomuqing/neptune/assets/128035413/ae1d196d-8177-4db3-ae1c-5f1d42bcc663)
![single](https://github.com/caomuqing/neptune/assets/128035413/c1ef2bce-2543-4fac-bd93-3685f5b26f92)
![TF_data_missing](https://github.com/caomuqing/neptune/assets/128035413/d175a770-917f-4f81-8069-22244bdcaaf8)

**Comment by caomuqing** [comment]
Basically, you have to make sure all the commands in [neptune_single_benchmark.sh](https://github.com/caomuqing/neptune/blob/main/neptune_single_benchmark.sh) are running. What you can do is to open a new terminal and run each command in the file, instead of running the commands using the xterm terminal. I assume you also have sourced the correct `setup.bash` file as indicated in my previous comment. If all commands are running (no error messages), I am pretty sure the program will work. If not, paste the error message here.

**Comment by caomuqing** [comment]
One thing you have to ensure is to run the [neptune_single_benchmark.sh](https://github.com/caomuqing/neptune/blob/main/neptune_single_benchmark.sh) file when you are in the directory `catkin_ws_neptune`. Otherwise, ROS does not correctly detect your node, which will result in the error in your previous comment `cannot launch node of type ...`

**Comment by churoc** [comment]
> So sorry that I wasn't able to operate for the last few days. After I tried the source file and the launch file as you told me, the two commands now work well, but the image is still the same as before, as shown in the picture, it shows the target's position and obstacles, the process of trajectory-searching and the actual route are missing. I don't think it's a source problem because I still can't generate a route after executing the instructions in the launch file one by one. I checked the display settings and most of them are good. It seems there's TF data missing , could that be the problem? As your article shows, the route consists of three lines of different colors, including the path generated by Kim's method, the trajectory generated by the front-end trajectory finder, and the actual trajectory after optimization. I want to figure out how the programming works and show the process in image so that I can see the effect more intuitively. If possible, I hope I can use different vichels to achieve some functions, which will be very helpful for my research content. Thanks a lot for your help! ![goal_image](https://user-images.githubusercontent.com/128035413/255182549-07c13370-96a4-4de5-ac6d-e883f94e9d61.jpg) ![displays](https://user-images.githubusercontent.com/128035413/255182585-ae1d196d-8177-4db3-ae1c-5f1d42bcc663.jpg) ![single](https://user-images.githubusercontent.com/128035413/255182642-c1ef2bce-2543-4fac-bd93-3685f5b26f92.jpg) ![TF_data_missing](https://user-images.githubusercontent.com/128035413/255182650-d175a770-917f-4f81-8069-22244bdcaaf8.jpg)

I also encountered the same error. After troubleshooting, I found that the issue was due to the lack of execution permissions for the Python files in the "scripts" directory. You can try running "chmod +x" on all the .py files and see if it resolves the problem.

**Comment by caomuqing** [comment]
Thanks @churoc for posting a potential solution. If no more issues, i will close this thread.
